spring.datasource.url=jdbc:postgresql://school_m8fv_user:6Uv00yue0mN9lIvVsDd4fNlCyMCrfq9x@dpg-d7tuchjbc2fs73eu88sg-a.oregon-postgres.render.com/school_m8fv_user
spring.datasource.username=school_m8fv_user
spring.datasource.password=6Uv00yue0mN9lIvVsDd4fNlCyMCrfq9x
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
