spring.datasource.url=jdbc:postgresql://dpg-d7tuchjbc2fs73eu88sg-a:5432/school_m8fv_user
spring.datasource.username=school_m8fv_user
spring.datasource.password=6Uv00yue0mN91IvVsDd4fN1CyMCrfq9x
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port cho Render
server.port=${PORT:10000}
